#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef MYBRAINTECHNOLOGIESSDK_SWIFT_H
#define MYBRAINTECHNOLOGIESSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import Realm.Swift;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MyBrainTechnologiesSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// <hr/>
/// <ul>
///   <li>
///     ChannelDatas
///   </li>
///   <li>
///   </li>
///   <li>
///     All values from one channel.
///   </li>
///   <li>
///   </li>
/// </ul>
/// <hr/>
SWIFT_CLASS("_TtC22MyBrainTechnologiesSDK12ChannelsData")
@interface ChannelsData : RealmSwiftObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Delegate to know if audio A2DP just connected or disconnected.
SWIFT_PROTOCOL("_TtP22MyBrainTechnologiesSDK24MBTBluetoothA2DPDelegate_")
@protocol MBTBluetoothA2DPDelegate
@optional
/// Called when the MBT Headset audio A2DP get connected.
- (void)audioA2DPDidConnect;
/// Called when the MBT Headset audio A2DP lost connection.
- (void)audioA2DPDidDisconnect;
/// Called to know if the Bluetooth Manager will try to connect A2DP from the BLE
- (BOOL)autoConnectionA2DPFromBLE SWIFT_WARN_UNUSED_RESULT;
@end


/// <hr/>
/// <ul>
///   <li>
///     MBTBluetoothEventDelegate
///   </li>
///   <li>
///   </li>
///   <li>
///     Event handler of the MBT Headset.
///   </li>
///   <li>
///   </li>
/// </ul>
/// <hr/>
SWIFT_PROTOCOL("_TtP22MyBrainTechnologiesSDK25MBTBluetoothEventDelegate_")
@protocol MBTBluetoothEventDelegate
@optional
/// Called when the bluetooth state change
/// \param isBluetoothOn A <em>Bool</em> Value which is true if the bluetooth device is PowerOn and false if is PowerOff
///
- (void)onBluetoothStateChange:(BOOL)isBluetoothOn;
/// Called when the headset has been connected
/// before the services and characteristics exploration.
- (void)onConnectionEstablished;
/// Called each time the BLE status change.
/// With a <em>Bool</em> informing if headset is connected or not
/// to the iDevice.
/// \param isConnected A <em>Bool</em> Value which is true if Melomind is connected in BLE and false if not.
///
- (void)onHeadsetStatusUpdate:(BOOL)isConnected;
/// Called if the SDK can’t connect to the MBT Headset,
/// with the error.
/// \param error A <em>Error</em> object which describe the cause of the failure (Core Bluetooth error) during the connection.
///
- (void)onConnectionFailed:(NSError * _Nullable)error;
/// Called when the headset lost connection.
/// \param error A <em>Error</em> object which describe the cause of the deconnection, can be a core Bluetooth error or MyBrainTechnologiesSDK error.
///
- (void)onConnectionBLEOff:(NSError * _Nullable)error;
/// Called when initiate timerUpdateBatteryLevel
/// returns -> schedules timerUpdateBatteryLevel with this timeInterval
- (NSTimeInterval)timeIntervalOnReceiveBattery SWIFT_WARN_UNUSED_RESULT;
/// Called after the connection in BLE of the Melomind if the Melomind need to be up date
- (void)onNeedToUpdate;
/// Called when respond from the Melomind that it is ready to receive the binary
- (void)onReadyToUpdate;
/// Called for each Step of the update and during the sending
/// \param progress A <em>Float</em> Value between 0 and 1 which represents the advance of the update
///
- (void)onProgressUpdate:(float)progress;
/// Called if the MyBrainTechnologie need the update of the Bluetooth Device
- (void)requireToRebootBluetooth;
/// Called if the Bluetooth Device reboot
- (void)onRebootBluetooth;
/// Called if the Update Finish
- (void)onUpdateComplete;
/// Called When the Update process fail
/// \param status <em>Int</em> give status fail
/// 0: CurrentVersion > Latest Bin Version
/// 1: OTA_MODE_EVT FAIL (0)
/// 2: OTA_STATUS_EVT FAIL (0)
/// 3: After Melomind Reboot, Latest Bin Version > CurrentVersion
///
- (void)onUpdateFailWithError:(NSError * _Nonnull)error;
@end

@class NSString;
@class MBTDeviceInformations;

/// Model to store data about the Headset connected.
SWIFT_CLASS("_TtC22MyBrainTechnologiesSDK9MBTDevice")
@interface MBTDevice : RealmSwiftObject
/// Device Name
@property (nonatomic, copy) NSString * _Nonnull deviceName;
/// Device informations from MBT Headset Bluetooth LE.
@property (nonatomic, strong) MBTDeviceInformations * _Nullable deviceInfos;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// <hr/>
/// <ul>
///   <li>
///     MBTDeviceAcquisitionDelegate
///   </li>
///   <li>
///   </li>
///   <li>
///     Manage the acquisition data communication outside the SDK.
///   </li>
///   <li>
///   </li>
/// </ul>
/// <hr/>
SWIFT_PROTOCOL("_TtP22MyBrainTechnologiesSDK28MBTDeviceAcquisitionDelegate_")
@protocol MBTDeviceAcquisitionDelegate
@optional
/// Called when receiving batteryLevel from BLE
/// \param battery level <em>batteryLevel</em> received.
///
- (void)onReceivingBatteryLevel:(NSInteger)levelBattery;
/// Called when
/// remarks:
///
/// 0 -> no saturation,
/// 1 -> left side saturation,
/// 2 -> right side Saturation
/// 3 -> both side Saturation
/// \param status A <em>Int</em> of the saturation headset
///
- (void)onReceivingSaturationStatus:(NSInteger)status;
@end


/// Device Informations model.
SWIFT_CLASS("_TtC22MyBrainTechnologiesSDK21MBTDeviceInformations")
@interface MBTDeviceInformations : RealmSwiftObject
/// The commercial name of the device.
@property (nonatomic, copy) NSString * _Nullable productName;
/// The product specific serial number.
@property (nonatomic, copy) NSString * _Nullable deviceId;
/// The product hardware version.
@property (nonatomic, copy) NSString * _Nullable hardwareVersion;
/// The product firmware version.
@property (nonatomic, copy) NSString * _Nullable firmwareVersion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class MBTEEGPacket;

/// Manage the acquisition data communication outside the SDK.
SWIFT_PROTOCOL("_TtP22MyBrainTechnologiesSDK25MBTEEGAcquisitionDelegate_")
@protocol MBTEEGAcquisitionDelegate
@optional
/// Called to each EEG package sent by the BLE.
/// \param dataArray <em>Dictionnary</em> of EEG data array.
///
- (void)onReceivingPackage:(MBTEEGPacket * _Nonnull)eegPacket;
@end


/// <hr/>
/// <ul>
///   <li>
///     MBTEEGPacket
///   </li>
///   <li>
///   </li>
///   <li>
///     Model to store processed data of an EEG Packet.
///   </li>
///   <li>
///   </li>
/// </ul>
/// <hr/>
SWIFT_CLASS("_TtC22MyBrainTechnologiesSDK12MBTEEGPacket")
@interface MBTEEGPacket : RealmSwiftObject
/// The timestamp in milliseconds when this packet is created.
@property (nonatomic) NSInteger timestamp;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
